// Applications seed data — plausible Thai booth-seller applicants.
// Status: new | reviewing | needs_info | approved | rejected

const SEED_APPLICATIONS = [
  {
    id: "APP-2026-0142",
    brand: "Petal & Pulp",
    owner: "Khun Aom",
    ownerFull: "Aom Sirikanya",
    initials: "AS",
    category: "Pet treats & supplements",
    phone: "+66 81 234 5678",
    email: "aom@petalandpulp.co",
    line: "@petalandpulp",
    ig: "@petalandpulp.bkk",
    location: "Bangkok · Phra Khanong",
    expectedEvents: 4,
    expectedRevenue: "฿80,000–150,000 / event",
    skuCount: 18,
    submitted: "3 hours ago",
    submittedAbs: "May 18, 2026 · 11:24",
    status: "new",
    pitch: "Single-protein freeze-dried treats for sensitive cats. Sold at theMeowseum Pet Expo for 2 years. Looking to scale to 4 events with Send Later fulfillment for cat-café partners.",
    referral: "Found via theMeowseum vendor email",
    pets: "2 cats (Mochi, Daikon)",
    activity: [
      { t: "11:24", date: "May 18", who: "Aom Sirikanya", what: "Submitted application", kind: "submit" }
    ]
  },
  {
    id: "APP-2026-0141",
    brand: "Mango Press",
    owner: "Khun Sun",
    ownerFull: "Sun Wiriyaporn",
    initials: "SW",
    category: "Risograph prints & zines",
    phone: "+66 89 911 2233",
    email: "hello@mangopress.studio",
    line: "@mangopress",
    ig: "@mango.press",
    location: "Chiang Mai · Nimman",
    expectedEvents: 6,
    expectedRevenue: "฿30,000–80,000 / event",
    skuCount: 42,
    submitted: "1 day ago",
    submittedAbs: "May 17, 2026 · 16:08",
    status: "new",
    pitch: "Two-color riso prints, mostly cats. We do Bangkok Art Book Fair + Chiang Mai Design Week. Need a way to capture customer emails for the print club without slowing the line.",
    referral: "Referred by Cattober Studio",
    pets: "1 cat (Foon)",
    activity: [
      { t: "16:08", date: "May 17", who: "Sun Wiriyaporn", what: "Submitted application", kind: "submit" }
    ]
  },
  {
    id: "APP-2026-0140",
    brand: "Khun Rin Scarves",
    owner: "Khun Rin",
    ownerFull: "Rin Asnachinda",
    initials: "RA",
    category: "Handpainted textiles",
    phone: "+66 86 778 4412",
    email: "rin@rinscarves.com",
    line: "@rinscarves",
    ig: "@rin.scarves",
    location: "Bangkok · Ari",
    expectedEvents: 3,
    expectedRevenue: "฿120,000–200,000 / event",
    skuCount: 24,
    submitted: "2 days ago",
    submittedAbs: "May 16, 2026 · 10:45",
    status: "new",
    pitch: "Hand-painted silk scarves, one-of-a-kind. Currently using a paper notebook at booths. High AOV means I lose sales when payment is slow.",
    referral: "Google search",
    pets: "—",
    activity: [
      { t: "10:45", date: "May 16", who: "Rin Asnachinda", what: "Submitted application", kind: "submit" }
    ]
  },
  {
    id: "APP-2026-0138",
    brand: "Studio Nara",
    owner: "Khun Nara",
    ownerFull: "Nara Charoenpong",
    initials: "NC",
    category: "Ceramic illustration",
    phone: "+66 82 145 9988",
    email: "studio@nara.co",
    line: "@studionara",
    ig: "@studio.nara",
    location: "Bangkok · Ekkamai",
    expectedEvents: 5,
    expectedRevenue: "฿60,000–100,000 / event",
    skuCount: 31,
    submitted: "3 days ago",
    submittedAbs: "May 15, 2026 · 09:12",
    status: "reviewing",
    pitch: "Hand-thrown ceramic mugs with cat illustrations. Sold at theMeowseum twice. The booth manager (P'Joom) said you'd be the right fit.",
    referral: "P'Joom (theMeowseum)",
    pets: "1 cat (Sushi)",
    activity: [
      { t: "09:12", date: "May 15", who: "Nara Charoenpong", what: "Submitted application", kind: "submit" },
      { t: "14:30", date: "May 16", who: "You", what: "Started reviewing", kind: "review" },
      { t: "10:08", date: "May 17", who: "You", what: "Verified IG account · 4.2k followers, active", kind: "note" }
    ]
  },
  {
    id: "APP-2026-0136",
    brand: "Cattober Studio",
    owner: "Khun Bow",
    ownerFull: "Bow Suksawat",
    initials: "BS",
    category: "Illustration & merch",
    phone: "+66 81 556 7723",
    email: "bow@cattober.studio",
    line: "@cattober",
    ig: "@cattober.studio",
    location: "Bangkok · Thonglor",
    expectedEvents: 8,
    expectedRevenue: "฿40,000–90,000 / event",
    skuCount: 56,
    submitted: "4 days ago",
    submittedAbs: "May 14, 2026 · 18:22",
    status: "reviewing",
    pitch: "Cat-themed illustration brand. Acrylic charms, stickers, prints. I do 8–10 events a year and currently juggle Excel + Google Form. The Send Later flow on your demo is exactly what I need.",
    referral: "Instagram ad",
    pets: "3 cats (Pim, Som, Yai)",
    activity: [
      { t: "18:22", date: "May 14", who: "Bow Suksawat", what: "Submitted application", kind: "submit" },
      { t: "11:00", date: "May 15", who: "You", what: "Started reviewing", kind: "review" }
    ]
  },
  {
    id: "APP-2026-0133",
    brand: "Banana & Co",
    owner: "Khun Ploy",
    ownerFull: "Ploy Kasemsri",
    initials: "PK",
    category: "Handmade pet collars",
    phone: "+66 88 102 4471",
    email: "ploy@bananaandco.shop",
    line: "@bananaco",
    ig: "@bananaandco",
    location: "Bangkok · Ladprao",
    expectedEvents: 12,
    expectedRevenue: "฿50,000–120,000 / event",
    skuCount: 88,
    submitted: "5 days ago",
    submittedAbs: "May 13, 2026 · 14:55",
    status: "reviewing",
    pitch: "Handmade leather collars and leashes, sized to order. Big booth: 12 events / year across BKK + CNX. Custom sizing means lots of Send Later orders.",
    referral: "Cattober Studio",
    pets: "5 cats, 2 dogs",
    activity: [
      { t: "14:55", date: "May 13", who: "Ploy Kasemsri", what: "Submitted application", kind: "submit" },
      { t: "09:30", date: "May 14", who: "You", what: "Started reviewing", kind: "review" },
      { t: "16:42", date: "May 16", who: "You", what: "Checked references with Cattober", kind: "note" }
    ]
  },
  {
    id: "APP-2026-0131",
    brand: "P'Joom Candles",
    owner: "Khun Joom",
    ownerFull: "Joom Tantipanichakul",
    initials: "JT",
    category: "Home goods",
    phone: "+66 87 224 9981",
    email: "joom@pjoomcandles.com",
    line: "@pjoom",
    ig: "@pjoom.candles",
    location: "Phuket · Patong",
    expectedEvents: 8,
    expectedRevenue: "฿70,000–110,000 / event",
    skuCount: 22,
    submitted: "6 days ago",
    submittedAbs: "May 12, 2026 · 10:18",
    status: "needs_info",
    pitch: "Soy candles, pet-safe scents. Mostly southern events + Bangkok holiday markets.",
    referral: "Direct",
    pets: "—",
    activity: [
      { t: "10:18", date: "May 12", who: "Joom Tantipanichakul", what: "Submitted application", kind: "submit" },
      { t: "15:00", date: "May 13", who: "You", what: "Started reviewing", kind: "review" },
      { t: "15:14", date: "May 13", who: "You", what: "Asked: can you share photos of a recent booth?", kind: "info" }
    ]
  },
  {
    id: "APP-2026-0128",
    brand: "Bento Pet",
    owner: "Khun Mint",
    ownerFull: "Mint Chaiyaphum",
    initials: "MC",
    category: "Pet meal kits",
    phone: "+66 89 445 1102",
    email: "mint@bentopet.co",
    line: "@bentopet",
    ig: "@bento.pet",
    location: "Bangkok · Sathorn",
    expectedEvents: 4,
    expectedRevenue: "฿100,000–180,000 / event",
    skuCount: 9,
    submitted: "1 week ago",
    submittedAbs: "May 11, 2026 · 13:40",
    status: "needs_info",
    pitch: "Subscription-style frozen meal kits for cats. Cold-chain logistics.",
    referral: "Direct",
    pets: "2 cats (Bento, Don)",
    activity: [
      { t: "13:40", date: "May 11", who: "Mint Chaiyaphum", what: "Submitted application", kind: "submit" },
      { t: "09:30", date: "May 12", who: "You", what: "Started reviewing", kind: "review" },
      { t: "09:45", date: "May 12", who: "You", what: "Asked: how do you handle cold-chain at booths?", kind: "info" }
    ]
  },
  {
    id: "APP-2026-0119",
    brand: "Khun Tan Patches",
    owner: "Khun Tan",
    ownerFull: "Tan Naruepol",
    initials: "TN",
    category: "Embroidered patches",
    phone: "+66 86 991 4423",
    email: "tan@tanpatches.com",
    line: "@tanpatches",
    ig: "@tan.patches",
    location: "Bangkok · Bang Rak",
    expectedEvents: 5,
    expectedRevenue: "฿20,000–50,000 / event",
    skuCount: 64,
    submitted: "2 weeks ago",
    submittedAbs: "May 4, 2026 · 11:08",
    status: "approved",
    inviteCode: "MOCHI-TANP-2026",
    workspace: "tanpatches.mochipos.app",
    pitch: "Embroidered cat patches and iron-ons. Low ticket, high volume.",
    referral: "Cattober Studio",
    pets: "1 cat (Mali)",
    activity: [
      { t: "11:08", date: "May 4",  who: "Tan Naruepol", what: "Submitted application", kind: "submit" },
      { t: "16:30", date: "May 5",  who: "You", what: "Started reviewing", kind: "review" },
      { t: "09:42", date: "May 7",  who: "You", what: "Approved · invite code MOCHI-TANP-2026 generated", kind: "approve" },
      { t: "09:42", date: "May 7",  who: "System", what: "Invite email sent to tan@tanpatches.com", kind: "email" },
      { t: "20:18", date: "May 8",  who: "Tan Naruepol", what: "Redeemed invite · workspace created", kind: "redeem" }
    ]
  },
  {
    id: "APP-2026-0112",
    brand: "Tiger Pottery",
    owner: "Khun Phai",
    ownerFull: "Phai Sangchan",
    initials: "PS",
    category: "Pet ceramics",
    phone: "+66 81 778 6612",
    email: "phai@tigerpottery.com",
    line: "@tigerpottery",
    ig: "@tiger.pottery",
    location: "Lampang",
    expectedEvents: 4,
    expectedRevenue: "฿60,000–110,000 / event",
    skuCount: 28,
    submitted: "3 weeks ago",
    submittedAbs: "Apr 27, 2026 · 14:20",
    status: "approved",
    inviteCode: "MOCHI-TIGR-2026",
    workspace: "tigerpottery.mochipos.app",
    pitch: "Hand-thrown pet food bowls. 4 events/yr in northern TH.",
    referral: "Direct",
    pets: "—",
    activity: [
      { t: "14:20", date: "Apr 27", who: "Phai Sangchan", what: "Submitted application", kind: "submit" },
      { t: "10:00", date: "Apr 28", who: "You", what: "Approved · invite code MOCHI-TIGR-2026 generated", kind: "approve" },
      { t: "10:00", date: "Apr 28", who: "System", what: "Invite email sent to phai@tigerpottery.com", kind: "email" },
      { t: "19:55", date: "Apr 29", who: "Phai Sangchan", what: "Redeemed invite · workspace created", kind: "redeem" },
      { t: "—",     date: "May 12", who: "System", what: "First sale recorded · ฿2,890", kind: "sale" }
    ]
  },
  {
    id: "APP-2026-0108",
    brand: "Nong Aim Vintage",
    owner: "Khun Aim",
    ownerFull: "Aim Boonyarit",
    initials: "AB",
    category: "Vintage / resale",
    phone: "+66 89 332 0011",
    email: "aim@nongaim.shop",
    line: "@nongaim",
    ig: "@nong.aim.vintage",
    location: "Bangkok · JJ Market",
    expectedEvents: 24,
    expectedRevenue: "฿15,000–30,000 / event",
    skuCount: 200,
    submitted: "3 weeks ago",
    submittedAbs: "Apr 25, 2026 · 13:02",
    status: "rejected",
    pitch: "Vintage clothing resale at JJ Market weekly.",
    referral: "Direct",
    pets: "—",
    activity: [
      { t: "13:02", date: "Apr 25", who: "Aim Boonyarit", what: "Submitted application", kind: "submit" },
      { t: "11:30", date: "Apr 27", who: "You", what: "Rejected · weekly market is outside our event-booth focus", kind: "reject" }
    ]
  },
  {
    id: "APP-2026-0102",
    brand: "Soysauce Studio",
    owner: "Khun Yui",
    ownerFull: "Yui Pongsiri",
    initials: "YP",
    category: "Illustration prints",
    phone: "+66 84 226 1199",
    email: "yui@soysauce.studio",
    line: "@soysauce",
    ig: "@soysauce.studio",
    location: "Bangkok · Sathorn",
    expectedEvents: 6,
    expectedRevenue: "฿35,000–70,000 / event",
    skuCount: 38,
    submitted: "2 hours ago",
    submittedAbs: "May 18, 2026 · 12:40",
    status: "new",
    pitch: "Illustrated prints and notebooks. I share a booth with Cattober Studio sometimes.",
    referral: "Cattober Studio",
    pets: "1 cat (Tofu)",
    activity: [
      { t: "12:40", date: "May 18", who: "Yui Pongsiri", what: "Submitted application", kind: "submit" }
    ]
  }
];

// Status meta — labels, swatches, dot color
const STATUS_META = {
  new:        { label: "New",         tone: "lav",     dot: "var(--lavender-700)" },
  reviewing:  { label: "Reviewing",   tone: "info",    dot: "var(--info)" },
  needs_info: { label: "Needs info",  tone: "warn",    dot: "var(--warn)" },
  approved:   { label: "Approved",    tone: "ok",      dot: "var(--success)" },
  rejected:   { label: "Rejected",    tone: "bad",     dot: "var(--danger)" }
};

const STATUS_ORDER = ["new", "reviewing", "needs_info", "approved", "rejected"];

Object.assign(window, { SEED_APPLICATIONS, STATUS_META, STATUS_ORDER });
